# Generated by Django 3.0.6 on 2020-08-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroFac1', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=20)),
                ('RUC', models.CharField(max_length=100)),
                ('extra', models.CharField(max_length=100)),
                ('rucEmpresa', models.CharField(max_length=100)),
            ],
        ),
    ]
